### PR TITLE
Tagged templates

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Supersedes GH-29 GH-38 

Implements GH-31

Precedes GH-21 GH-34 GH-35 GH-39 

This patch touches almost every line of code currently present. It implements GH-31 mostly, but should provide the groundworks to further expand upon. Also implementing tests as we go to verify features work as advertised.

The most notable change is that this patch now uses `falafel` to modify esprima nodes, as seen in [hyperxify](https://github.com/substack/hyperxify). This allows require calls to work both with template strings as with file requires.

## progress
- [x] detect and namespace template strings
- [x] write tests for template string modification
- [x] detect, read, and namespace files from disk
- [x] write tests for reading and transforming files
- [x] write tests for server - returns prefix if vanilla node
- [ ] write tests for correct plugin resolution
- [x] write tests for CSS injection in header in transform

### CODE REVIEW

**Comment by ahdinosaur** [comment]
nice work @yoshuawuyts, this looks great. :)

just wondering, is our intention for `sheetify` to only work with `browserify`, or do we want it to also work when running in node (be "universal")? https://github.com/sheetify/sheetify/issues/32 did a great job of focusing us on the `browserify` use case, but i imagine we still want to use our stylesheets (including support for template strings) during server-side rendering. i'm thinking in particular of changing `require('sheetify')` to return the `browserify` transform, which seems would break using `sheetify` in node. just wondering what's on your mind here and still very much in support of your progress.

:sparkle:

**Comment by yoshuawuyts** [comment]
@ahdinosaur excellent question! To be honest I haven't thought about the server story at all, so far I've been focused on getting it working in the browser. I agree it should tho; I'll switch the files back again and add bullet points for server support. Heaps good that you're raising this now, thanks haha ✨

**Comment by yoshuawuyts** [comment]
Hmh, if I'm not mistaken all that's needed for JS apps to render correctly on the server is to return the right `prefix` - which if I'm not mistaken should be the case again now that `index.js` points at the right file again; but I'll add tests!

**Comment by yoshuawuyts** [comment]
cool, server prefixing tests added in https://github.com/sheetify/sheetify/commit/d560fb71a678b227be06b9bd14861356e7faa8b1 :sparkles:

**Comment by ahdinosaur** [comment]
cheers. don't we want to support server-side tagged templates and relative file paths as well? (happy to put this off for another task, just wondering)

**Comment by yoshuawuyts** [comment]
Fixed server side tagged templates in cffbc21 (and added tests), haven't run into relative paths yet but I'll fix when I do; first off is reading from disk and making sure transforms are resolved

**Comment by yoshuawuyts** [comment]
Alright, reading from both disk and template strings works now; on both client and server. Upgrade path to also exorcise to external files + trigger `change` events is present too. All that's left now is add tests that plugins are correctly executed and this patch should be good to go :sparkles:

**Comment by yoshuawuyts** [comment]
ps. 85% test coverage across the board; we're getting there

**Comment by yoshuawuyts** [comment]
manually tested and confirmed plugins work; writing test + docs now

**Comment by yoshuawuyts** [comment]
Alright, cool! So this is now ready for review. Not all tests have been added (damn you `jsdom`) but I've run some manual tests and both cli and js seem to be working well! Example code to play around with can be found on [playground-virtual-dom](https://github.com/yoshuawuyts/playground-virtual-app/blob/master/index.js).

I'll create an issue for which tests are missing, but I reckon we shouldn't make it a blocker. Hope this is all ok!

Final issue that's in here (and I don't quite like) is that this is now our syntax:
```sh
$ browserify -t sheetify/transform > bundle.js
```
Not sure if there's a way to make browserify detect that `transform` is the file it needs; suggestions welcome! We can merge this patch even if we don't solve it, as any fixes to this will be backwards compatible.

Also: I'm too lazy to change the committer name, if someone wants to: feel free to force push. Thanks! :sparkles:

cc/ @ahdinosaur

**Comment by yoshuawuyts** [comment]
Alright, I'm going to merge this. Not releasing v4 quite yet as the other issues haven't been resolved - but this enables us to solve them. If there are any issues - don't hesitate to raise them. Cheers! ✨

**Comment by ahdinosaur** [comment]
:tada: :cake:

**Pull request closed without merging**
